# This reusable workflow can be called from .NET repository to deploy published folder to IIS.

name: Deploy PR

on:
  workflow_call:
    inputs:
      repo-name:
        description: "Name of the repository"
        required: true
        type: string
        default: "HRMS.Api"
      operating-systems:
        description: "Optional input to set a list of operating systems which the workflow uses. Defaults to ['self-hosted'] if not set"
        required: false
        type: string
        default: "['self-hosted']"
      publish-folder:
        description: "Folder to publish"
        required: true
        type: string
        default: "./publish"
      deploy-folder:
        description: "Deployment destination folder"
        required: true
        type: string
        default: "C:\\CDC Team 4"

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:
    runs-on: ${{matrix.operating-systems}}
    strategy:
      fail-fast: false
      matrix:
        operating-systems: ${{fromJson(inputs.operating-systems)}}

    steps:
      - name: Publish
        run: dotnet publish --output ${{inputs.publish-folder}}
      - name: Turn off IIS
        run: iisreset /stop
      - name: Copy publish files
        run: Copy-Item ${{inputs.publish-folder}}/* "${{inputs.deploy-folder}}\API\${{inputs.repo-name}}" -Recurse -Force
      - name: Turn on IIS
        if: always()
        run: iisreset /start